In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {'creatures': ['Eagles', 'Eagles', 'Ducks', 'Herons', 'Herons',
'Eagles', 'Ducks', 'Eagles', 'Herons', 'Herons', 'Eagles'],
 'weight': [2.0, 5, 3.0, np.nan, 7, 2.5, 6, np.nan, 9, 3, 2.0],
 'frequency': [1, 3, 2, 5, 2, 3, 1, 3, 4, 2, 1],
 'status': ['no', 'no', 'yes', np.nan, 'yes', 'yes', 'yes', 'no', 'yes', 'yes',
'no'],
 'height': [1.2, 2.5, 1.8, 3.0, 2.2, 1.9, 2.6, 1.4, 2.8, 2.3, 1.1],
 'region': ['North', 'South', 'East', 'West', 'North', 'South', 'East',
'West', 'North', 'East', 'South'],
 'danger_level': ['low', 'medium', 'high', 'low', 'high', 'medium',
'high', 'low', 'medium', 'high', 'low']}
labels = ['x', 'y', 'z', 'w', 'v', 'u', 't', 's', 'r', 'q', 'p']
df=pd.DataFrame(data,columns=labels)

In [3]:
df.head()

Empty DataFrame
Columns: [x, y, z, w, v, u, t, s, r, q, p]
Index: []

I. Write a program to create a DataFrame named df from the 
above dictionary data, using labels as the index.

In [4]:
df=pd.DataFrame(data,index=[labels])
df

  creatures  weight  frequency status  height region danger_level
x    Eagles     2.0          1     no     1.2  North          low
y    Eagles     5.0          3     no     2.5  South       medium
z     Ducks     3.0          2    yes     1.8   East         high
w    Herons     NaN          5    NaN     3.0   West          low
v    Herons     7.0          2    yes     2.2  North         high
u    Eagles     2.5          3    yes     1.9  South       medium
t     Ducks     6.0          1    yes     2.6   East         high
s    Eagles     NaN          3     no     1.4   West          low
r    Herons     9.0          4    yes     2.8  North       medium
q    Herons     3.0          2    yes     2.3   East         high
p    Eagles     2.0          1     no     1.1  South          low

II. Write a program to display the basic information of the DataFrame, including its summary statistics and data types.

In [5]:
df.info()

<class 'pandas.DataFrame'>
MultiIndex: 11 entries, ('x',) to ('p',)
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   creatures     11 non-null     str
 1   weight        9 non-null      float64
 2   frequency     11 non-null     int64
 3   status        10 non-null     str
 4   height        11 non-null     float64
 5   region        11 non-null     str
 6   danger_level  11 non-null     str
dtypes: float64(2), int64(1), str(4)
memory usage: 731.0+ bytes

In [6]:
df.describe()

         weight  frequency     height
count  9.000000  11.000000  11.000000
mean   4.388889   2.454545   2.072727
std    2.497221   1.293340   0.646670
min    2.000000   1.000000   1.100000
25%    2.500000   1.500000   1.600000
50%    3.000000   2.000000   2.200000
75%    6.000000   3.000000   2.550000
max    9.000000   5.000000   3.000000

In [7]:
df.dtypes

creatures           str
weight          float64
frequency         int64
status              str
height          float64
region              str
danger_level        str
dtype: object

III. Write a program to display every alternate row of the DataFrame (starting from index 0).

In [8]:
df.iloc[0::2]

  creatures  weight  frequency status  height region danger_level
x    Eagles     2.0          1     no     1.2  North          low
z     Ducks     3.0          2    yes     1.8   East         high
v    Herons     7.0          2    yes     2.2  North         high
t     Ducks     6.0          1    yes     2.6   East         high
r    Herons     9.0          4    yes     2.8  North       medium
p    Eagles     2.0          1     no     1.1  South          low

IV. Write a program to display only rows at index positions 1st,3rd, and 7th from columns creatures and weight of the DataFrame.

In [9]:
df.iloc[[1,3,7],[0,1]]

  creatures  weight
y    Eagles     5.0
w    Herons     NaN
s    Eagles     NaN

V. Write a program to select and display the rows where the frequency is less than 4.

In [10]:
result=df[df['frequency']<4]
print(result)

  creatures  weight  frequency status  height region danger_level
x    Eagles     2.0          1     no     1.2  North          low
y    Eagles     5.0          3     no     2.5  South       medium
z     Ducks     3.0          2    yes     1.8   East         high
v    Herons     7.0          2    yes     2.2  North         high
u    Eagles     2.5          3    yes     1.9  South       medium
t     Ducks     6.0          1    yes     2.6   East         high
s    Eagles     NaN          3     no     1.4   West          low
q    Herons     3.0          2    yes     2.3   East         high
p    Eagles     2.0          1     no     1.1  South          low

VI. Write a program to select and display all rows where there are NaN values in the columns weight or status.

In [11]:
df[df['weight'].isnull()|df['status'].isnull()]

  creatures  weight  frequency status  height region danger_level
w    Herons     NaN          5    NaN     3.0   West          low
s    Eagles     NaN          3     no     1.4   West          low

VII. Write a program to fill the NaN values in the DataFrame with the mode (most frequent value) of the respective columns.

In [12]:
m=df.mode().iloc[0]
df.fillna

<bound method NDFrame.fillna of   creatures  weight  frequency status  height region danger_level
x    Eagles     2.0          1     no     1.2  North          low
y    Eagles     5.0          3     no     2.5  South       medium
z     Ducks     3.0          2    yes     1.8   East         high
w    Herons     NaN          5    NaN     3.0   West          low
v    Herons     7.0          2    yes     2.2  North         high
u    Eagles     2.5          3    yes     1.9  South       medium
t     Ducks     6.0          1    yes     2.6   East         high
s    Eagles     NaN          3     no     1.4   West          low
r    Herons     9.0          4    yes     2.8  North       medium
q    Herons     3.0          2    yes     2.3   East         high
p    Eagles     2.0          1     no     1.1  South          low>

VIII. Write a program to find the total number of frequency visits for the bird 'Herons'.

In [13]:
total=df[df['creatures']=='Herons']['frequency'].sum()
print("total number of freaquency visits for herons = ",total)

total number of freaquency visits for herons =  13

IX. Write a program to count and display the number of each type of creature in the DataFrame.

In [14]:
df["creatures"].value_counts()

creatures
Eagles    5
Herons    4
Ducks     2
Name: count, dtype: int64

X. Write a program to remove duplicate rows from the DataFrame df permanently. Display the DataFrame after the changes.

In [15]:
df.drop_duplicates(inplace=True)
df

  creatures  weight  frequency status  height region danger_level
x    Eagles     2.0          1     no     1.2  North          low
y    Eagles     5.0          3     no     2.5  South       medium
z     Ducks     3.0          2    yes     1.8   East         high
w    Herons     NaN          5    NaN     3.0   West          low
v    Herons     7.0          2    yes     2.2  North         high
u    Eagles     2.5          3    yes     1.9  South       medium
t     Ducks     6.0          1    yes     2.6   East         high
s    Eagles     NaN          3     no     1.4   West          low
r    Herons     9.0          4    yes     2.8  North       medium
q    Herons     3.0          2    yes     2.3   East         high
p    Eagles     2.0          1     no     1.1  South          low

XI. Write a program to replace the status of 'no' to 'not available' for all occurrences in the DataFrame df.

In [16]:
df['status'].replace('no','not available',inplace=True)
df

C:\Users\ankit\AppData\Local\Temp\ipykernel_16220\2418078538.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['status'].replace('no','not available',inplace=True)

  creatures  weight  frequency status  height region danger_level
x    Eagles     2.0          1     no     1.2  North          low
y    Eagles     5.0          3     no     2.5  South       medium
z     Ducks     3.0          2    yes     1.8   East         high
w    Herons     NaN          5    NaN     3.0   West          low
v    Herons     7.0          2    yes     2.2  North         high
u    Eagles     2.5          3    yes     1.9  South       medium
t     Ducks     6.0          1    yes     2.6   East         high
s    Eagles     NaN          3     no     1.4   West          low
r    Herons     9.0          4    yes     2.8  North       medium
q    Herons     3.0          2    yes     2.3   East         high
p    Eagles     2.0          1     no     1.1  South          low

XII. Write a program to add a new column size to the DataFrame df, where the values are based on the height column: label any bird taller than 2.5 as 'Large', otherwise label as 'Small'.

In [17]:
df["size"] = df["height"].apply(lambda x: "Large" if x>2.5 else "small")
df

  creatures  weight  frequency status  height region danger_level   size
x    Eagles     2.0          1     no     1.2  North          low  small
y    Eagles     5.0          3     no     2.5  South       medium  small
z     Ducks     3.0          2    yes     1.8   East         high  small
w    Herons     NaN          5    NaN     3.0   West          low  Large
v    Herons     7.0          2    yes     2.2  North         high  small
u    Eagles     2.5          3    yes     1.9  South       medium  small
t     Ducks     6.0          1    yes     2.6   East         high  Large
s    Eagles     NaN          3     no     1.4   West          low  small
r    Herons     9.0          4    yes     2.8  North       medium  Large
q    Herons     3.0          2    yes     2.3   East         high  small
p    Eagles     2.0          1     no     1.1  South          low  small

XIII. Write a program to sort the DataFrame df by height in descending order.

In [18]:
sorted_df=df.sort_values(by=['height'],ascending=[False])
sorted_df

  creatures  weight  frequency status  height region danger_level   size
w    Herons     NaN          5    NaN     3.0   West          low  Large
r    Herons     9.0          4    yes     2.8  North       medium  Large
t     Ducks     6.0          1    yes     2.6   East         high  Large
y    Eagles     5.0          3     no     2.5  South       medium  small
q    Herons     3.0          2    yes     2.3   East         high  small
v    Herons     7.0          2    yes     2.2  North         high  small
u    Eagles     2.5          3    yes     1.9  South       medium  small
z     Ducks     3.0          2    yes     1.8   East         high  small
s    Eagles     NaN          3     no     1.4   West          low  small
x    Eagles     2.0          1     no     1.2  North          low  small
p    Eagles     2.0          1     no     1.1  South          low  small

XIV. Write a program to reset the index of the DataFrame df to the default integer index, without affecting the original index.

In [19]:
df.reset_index()

,level_0,creatures,weight,frequency,status,height,region,danger_level,size
0,x,Eagles,2.0,1,no,1.2,North,low,small
1,y,Eagles,5.0,3,no,2.5,South,medium,small
2,z,Ducks,3.0,2,yes,1.8,East,high,small
3,w,Herons,NaN,5,NaN,3.0,West,low,Large
4,v,Herons,7.0,2,yes,2.2,North,high,small
5,u,Eagles,2.5,3,yes,1.9,South,medium,small
6,t,Ducks,6.0,1,yes,2.6,East,high,Large
7,s,Eagles,NaN,3,no,1.4,West,low,small
8,r,Herons,9.0,4,yes,2.8,North,medium,Large
9,q,Herons,3.0,2,yes,2.3,East,high,small
10,p,Eagles,2.0,1,no,1.1,South,low,small

XV. Write a program to create a new DataFrame df_copy by selecting only the rows where weight is greater than 5, and include only the columns creatures, weight, and region.

In [20]:
df_copy=df[df["weight"]>5][["creatures","weight","region"]]
df_copy

  creatures  weight region
v    Herons     7.0  North
t     Ducks     6.0   East
r    Herons     9.0  North