In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [6]:
df=pd.read_csv('Modified_Mobile_Price_Data.csv')

In [37]:
df.sample(14)

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
337,668,0,2.3,0,2,1,48,0.3,114,1,...,195,1292,1201,14,12,4,1,1,0,3305
1727,1564,0,1.4,0,5,1,26,0.1,129,6,...,117,1115,3742,13,3,13,1,1,0,34046
1542,1908,0,0.5,0,9,1,30,1.0,111,2,...,140,1046,2944,19,17,17,1,0,1,31914
1522,826,1,2.4,1,14,1,57,0.6,117,2,...,1077,1183,1907,15,14,5,1,0,0,12724
1614,1001,0,2.8,1,1,0,40,0.2,117,3,...,922,1836,3654,13,9,10,1,1,1,42397
813,721,1,1.3,1,10,0,16,0.9,125,1,...,408,1862,1713,10,3,4,0,1,1,10228
1203,1487,0,0.5,0,6,1,57,0.7,84,3,...,140,768,2563,18,4,14,1,0,0,20686
173,1577,0,0.5,1,0,1,42,0.3,197,5,...,1045,1737,2060,19,6,12,1,0,0,21744
208,664,1,1.1,1,1,1,51,0.1,110,7,...,701,1478,3629,19,15,6,1,1,1,34724
843,1438,1,1.8,0,3,0,16,0.6,169,8,...,859,867,2246,14,11,15,0,0,0,20401
1327,948,0,2.3,0,14,0,22,0.1,173,5,...,257,1654,3499,11,7,19,1,1,1,33519
1774,579,1,2.5,0,3,0,7,1.0,89,8,...,808,1517,2908,12,4,11,0,0,1,21650
287,1563,0,2.4,0,0,1,24,0.2,170,8,...,142,1699,3660,7,5,5,1,1,0,37020
715,817,0,1.3,0,0,0,11,0.5,144,3,...,722,766,2039,11,6,19,0,1,0,13143

In [15]:
X=df.iloc[:,:-1]
Y=df.iloc[:,-1]

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3 , random_state=0)

In [18]:
X_train.sample(3)

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,pc,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi
1251,1317,0,1.8,1,2,0,43,0.5,113,5,3,179,613,3436,16,13,5,0,1,1
1384,1163,1,1.9,0,6,0,2,0.9,133,5,20,919,1076,1568,14,0,19,1,0,0
644,1715,0,1.9,0,4,1,3,0.1,171,5,6,79,1652,514,7,4,13,1,0,0

In [20]:
lr=LinearRegression()
lr.fit(X_train,y_train)

LinearRegression()

In [23]:
y_pred=lr.predict(X_test)

In [27]:
from sklearn.preprocessing import StandardScaler

In [29]:
s = StandardScaler()

new_X_train = s.fit_transform(X_train)
new_X_test = s.transform(X_test)

In [30]:
new_lr = LinearRegression()

new_lr.fit(new_X_train,y_train)

LinearRegression()

In [31]:
new_X_train

array([[-0.90893609,  1.01149463, -1.16524008, ...,  0.55534783,
        -0.98722446,  0.98159786],
       [ 0.42822183,  1.01149463,  1.65523128, ...,  0.55534783,
        -0.98722446, -1.01874713],
       [-0.84784765,  1.01149463, -0.30683575, ...,  0.55534783,
         1.01294087,  0.98159786],
       ...,
       [-0.10121125, -0.98863599,  0.55156858, ..., -1.80067327,
        -0.98722446,  0.98159786],
       [-0.09894872, -0.98863599,  1.04208533, ...,  0.55534783,
         1.01294087,  0.98159786],
       [-1.19627797, -0.98863599, -1.28786926, ...,  0.55534783,
        -0.98722446,  0.98159786]], shape=(1400, 20))

In [32]:
new_X_test

array([[ 0.49609787,  1.01149463, -1.28786926, ...,  0.55534783,
         1.01294087, -1.01874713],
       [-0.32293964,  1.01149463, -1.28786926, ..., -1.80067327,
         1.01294087, -1.01874713],
       [ 0.65447529,  1.01149463,  0.3063102 , ...,  0.55534783,
        -0.98722446,  0.98159786],
       ...,
       [ 1.1001946 ,  1.01149463, -1.28786926, ...,  0.55534783,
         1.01294087,  0.98159786],
       [-1.47683226, -0.98863599, -1.28786926, ..., -1.80067327,
         1.01294087,  0.98159786],
       [-1.51982042,  1.01149463, -1.28786926, ...,  0.55534783,
         1.01294087, -1.01874713]], shape=(600, 20))

In [33]:
new_y_pred = new_lr.predict(new_X_test)

In [38]:
df1=sns.load_dataset("mpg")
df1

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10

In [39]:
X=df.iloc[:,:-1]
Y=df.iloc[:,-1]

In [40]:
X_train.sample(3)

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,pc,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi
1719,833,1,0.6,1,0,1,27,0.3,145,4,2,649,1290,586,19,8,19,1,0,1
1727,1564,0,1.4,0,5,1,26,0.1,129,6,16,117,1115,3742,13,3,13,1,1,0
1946,590,1,1.2,1,0,0,32,0.4,141,6,1,227,509,1817,10,0,6,0,1,0