In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [2]:
df=pd.read_csv('Modified_Mobile_Price_Data.csv')

In [3]:
df.sample(14)

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
110,783,0,1.8,1,0,1,43,1.0,106,3,...,1198,1471,2016,16,4,18,1,1,0,11088
1974,915,1,0.5,1,9,1,33,0.3,199,2,...,503,986,2156,7,3,13,1,1,0,12606
1772,1577,0,1.0,1,0,1,64,0.1,105,3,...,116,1432,2967,7,3,7,1,1,1,38459
1485,742,1,2.3,0,0,0,21,0.7,104,8,...,875,925,331,11,8,7,1,0,0,4838
1918,772,0,1.0,1,0,1,23,0.6,97,7,...,317,1805,2782,7,0,17,1,0,0,19692
406,1007,0,2.0,0,0,0,45,0.1,95,5,...,1186,1529,3648,9,0,16,0,0,0,42762
1516,1081,1,1.9,1,13,1,42,0.1,101,7,...,83,816,2456,7,4,7,1,0,0,11799
863,1425,0,1.2,0,9,1,35,0.7,127,8,...,150,1897,590,13,2,6,1,1,1,4863
862,1065,1,0.5,0,0,1,14,0.7,89,2,...,188,928,3078,10,1,18,1,0,1,22317
747,1648,1,0.5,0,1,1,17,0.9,142,2,...,1119,1238,1184,6,2,2,1,0,1,14670
942,1061,1,2.1,0,3,1,52,0.1,109,7,...,138,1330,999,16,12,9,1,1,0,3586
21,1709,1,2.1,0,1,0,13,1.0,156,2,...,974,1385,3283,17,1,15,1,0,0,40747
1486,1143,0,1.2,1,1,1,22,1.0,125,3,...,1116,1724,1214,12,5,16,1,1,0,13056
1070,1659,1,2.5,0,2,0,41,0.1,88,7,...,787,1515,545,12,0,9,0,1,1,5509

In [7]:
X=df.iloc[:,:-1]
Y=df.iloc[:,-1]

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3 , random_state=0)

In [10]:
X_train.sample(3)

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,pc,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi
502,1661,1,0.8,1,1,1,6,1.0,109,7,2,594,1337,864,9,8,2,1,0,1
1875,868,1,0.9,0,5,0,5,0.4,137,4,7,40,1311,1519,13,0,2,0,0,1
850,840,0,0.6,0,0,1,63,0.8,137,7,19,987,1081,3486,12,8,18,1,1,0

In [11]:
lr=LinearRegression()
lr.fit(X_train,y_train)

LinearRegression()

In [12]:
y_pred=lr.predict(X_test)

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
s = StandardScaler()

new_X_train = s.fit_transform(X_train)
new_X_test = s.transform(X_test)

In [15]:
new_lr = LinearRegression()

new_lr.fit(new_X_train,y_train)

LinearRegression()

In [16]:
new_X_train

array([[-0.90893609,  1.01149463, -1.16524008, ...,  0.55534783,
        -0.98722446,  0.98159786],
       [ 0.42822183,  1.01149463,  1.65523128, ...,  0.55534783,
        -0.98722446, -1.01874713],
       [-0.84784765,  1.01149463, -0.30683575, ...,  0.55534783,
         1.01294087,  0.98159786],
       ...,
       [-0.10121125, -0.98863599,  0.55156858, ..., -1.80067327,
        -0.98722446,  0.98159786],
       [-0.09894872, -0.98863599,  1.04208533, ...,  0.55534783,
         1.01294087,  0.98159786],
       [-1.19627797, -0.98863599, -1.28786926, ...,  0.55534783,
        -0.98722446,  0.98159786]], shape=(1400, 20))

In [17]:
new_X_test

array([[ 0.49609787,  1.01149463, -1.28786926, ...,  0.55534783,
         1.01294087, -1.01874713],
       [-0.32293964,  1.01149463, -1.28786926, ..., -1.80067327,
         1.01294087, -1.01874713],
       [ 0.65447529,  1.01149463,  0.3063102 , ...,  0.55534783,
        -0.98722446,  0.98159786],
       ...,
       [ 1.1001946 ,  1.01149463, -1.28786926, ...,  0.55534783,
         1.01294087,  0.98159786],
       [-1.47683226, -0.98863599, -1.28786926, ..., -1.80067327,
         1.01294087,  0.98159786],
       [-1.51982042,  1.01149463, -1.28786926, ...,  0.55534783,
         1.01294087, -1.01874713]], shape=(600, 20))

In [18]:
new_y_pred = new_lr.predict(new_X_test)

In [19]:
df1=sns.load_dataset("mpg")
df1

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10

In [20]:
X=df.iloc[:,:-1]
Y=df.iloc[:,-1]

In [21]:
X_train.sample(3)

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,pc,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi
653,571,0,1.6,1,8,0,35,0.2,186,7,20,177,1282,2598,13,5,8,1,1,0
143,786,0,2.2,1,0,0,33,0.5,141,7,6,507,1697,2390,12,11,5,1,0,1
131,1790,0,2.5,1,9,0,2,0.1,184,1,14,622,792,1366,7,0,20,1,1,1